version: "3.4"
services:
  redis:
    container_name: redis
    image: redis:3.2.12-alpine
    command: sh redis.sh
    environment:
      CC_REDIS_HOST: ${CC_REDIS_HOST}
      CC_REDIS_PORT: ${CC_REDIS_PORT}
      CC_REDIS_PASSWORD: ${CC_REDIS_PASSWORD}
    working_dir: /app
    volumes:
      - ./redis.sh:/app/redis.sh
